name: "Push to feature branch"
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!develop'
      - '!stage'
      - '!main'
    
  pull_request:
    branches:
      - main

env:
  aws_role_to_assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
  aws_default_region: eu-west-2
  terraform_version: ${{ secrets.TERRAFORM_VERSION }}
  ssh_private_key:
    ${{ secrets.SSH_PRIVATE_KEY }}
    #${{ secrets.LN_SSH_PRIVATE_KEY }}

jobs:
  build-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: files/accounts/datascience/environments/eu-west-2/wise

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.ssh_private_key }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.aws_role_to_assume }}
          aws-region: ${{ env.aws_default_region }}

      # Terraform checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ env.ssh_private_key }}
          fetch-depth: 0
          #ref: ${{ github.head_ref }}

      # Install the selected version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform Init
        id: init
        run: terraform init -get=true -input=false -reconfigure

      # Run a terraform fmt to check syntax
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -check -diff

      # Run a terraform validate
      - name: Terraform Validate
        id: validate
        if: success() || failure()
        run: terraform validate

      # Run a terraform plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -lock=false -refresh=true